Repository ROCm/rocRAND, pull requests merged in 2024-06, with the labels that each got.

#502 cmake: don't set CMAKE_C_COMPILER, as rocRAND is a CXX project
  .gitlab-ci.yml
  cmake/Dependencies.cmake
  test/cpp_wrapper/cmake/Dependencies.cmake
  toolchain-linux.cmake
  toolchain-windows.cmake
Labels: ci:static-libraries

#499 Suggest clang-format changes on PRs
  .github/workflows/clang-format-check.yml
  clang-format-diff.sh
  scripts/clang-format/clang-format-apply.sh
Labels: noCI

#507 cherry picking documentation from develop into 6.2
  .readthedocs.yaml
  LICENSE.txt
  docs/api-reference-home.rst
  docs/api-reference/cpp-api.rst
  docs/api-reference/python-api.rst
  docs/conceptual/curand-compatibility.rst
  docs/conceptual/dynamic_ordering_configuration.rst
  docs/conceptual/programmers-guide.rst
  docs/index.rst
  docs/install/installing.rst
  docs/sphinx/_toc.yml.in
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  docs/what-is-rocrand.rst
Labels: ci:docs-only
